### ISSUE TITLE
Tested on macOS High Sierra

### ISSUE THREAD

**Issue by JARVIS-AI** [fetacore/Infinitex#5]
Hello
My OS version is **High Sierra 10.13.4**

I clone your project and install packages and after run with ``npm start`` I get these issues
I tried to fix the error said : ``Electron could not be found. No hard resets for you!`` but no luck yet. 

I will working on this project because of I like it

#### Some suggestions :
1. Need **better UI** (More understandable and clean)
2. Better **UX** in packaged app (Buttons - Colors - Sides ...)

For now I remember these

Overall app runs and seems working but need alot of major fixes, improvements specially for mac design need some clean UI and smooth UX

**Note :** I didn't bundled the app yet just **npm start**, not run in dist folder

#### Errors and Bugs :

1. Mac Menu Bar going crazy and I don't know what's cause that freaking issue 
2. ``(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.``
3. ``Electron could not be found. No hard resets for you!``
4. ``[55984:1102/212802.295773:ERROR:CONSOLE(506)] "Uncaught TypeError: Cannot read property 'nodeType' of null", source: chrome-devtools://devtools/bundled/elements/elements_module.js (506)``
5. ``2018-11-02 21:28:05.888 Electron Helper[57283:5162458] Couldn't set selectedTextBackgroundColor from default ()``

For now of course
I'm still playing with it ⚙️

#### Fixes I tried : 
For ``Electron could not be found. No hard resets for you!`` i tried the full path but no success

> Index.js
```js
if (isDevMode) {
  // require('electron-reload')(__dirname)} //Not Working : Electron not found, no hard reset
  require('electron-reload')(__dirname, { electron: path.join(__dirname, 'node_modules', '.bin', 'electron') })}
```

#### Shots :

These of shots from testing

> Devmode app light
---
![IMG-1](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Projects/InfinitTex/IMG-1.png)

> Dev Mode app dark
---
![IMG-4](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Projects/InfinitTex/IMG-4.png)

> Dev Mode app expanded
---
![IMG-3](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Projects/InfinitTex/IMG-3.png)

> Error within Inspector
---
![IMG-2](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Projects/InfinitTex/IMG-2-2.png)

> macOS Menu Issue (White Logo, I think 🤔)
---
![IMG-5](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Projects/InfinitTex/IMG-5.png)

> Terminal running log
---
![IMG-6](https://raw.githubusercontent.com/JARVIS-AI/img-storageprojects/master/Projects/InfinitTex/IMG-6-6.png)

Thanks for reading
I'll be in touch if you have any question
I love the Idea of **InfinitTex**

**Comment by JARVIS-AI** [comment]
Can't build app 
```
➜ npm run dist

> InfiniTex@0.9.15 dist /Users/jarvismercer/Desktop/Infinitex
> node ./beforePackage.js && cd prod && yarn && electron-builder

yarn install v1.9.4
(node:67695) ExperimentalWarning: The fs.promises API is experimental
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info google-closure-compiler-linux@20180910.0.1: The platform "darwin" is incompatible with this module.
info "google-closure-compiler-linux@20180910.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > pdfjs-dist@2.0.402" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".
warning "pdfjs-dist > worker-loader@1.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".
warning "react-pdf > pdfjs-dist@2.0.305" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 1043.79s.
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=4.0.0-nightly.20181010 appOutDir=dist/mac
  • compiling using electron-compile
(node:68771) ExperimentalWarning: The fs.promises API is experimental
[xmldom error]  invalid doc source
@#[line:0,col:undefined]
TypeError: Cannot read property 'documentElement' of undefined
    at parse (/Users/jarvismercer/Desktop/Infinitex/node_modules/plist/lib/parse.js:68:9)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/electron/electronMac.ts:51:25
From previous event:
    at createMacApp (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/out/electron/electronMac.js:245:17)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:75:11
    at Generator.next (<anonymous>)
From previous event:
    at beforeCopyExtraFiles (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/out/electron/ElectronFramework.js:147:17)
    at beforeCopyExtraFiles (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:150:14)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/platformPackager.ts:222:13
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at MacPackager.doPack (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/jarvismercer/Desktop/Infinitex/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:166:5)
From previous event:
    at Packager.doBuild (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:152:20)
From previous event:
    at Packager._build (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/Users/jarvismercer/Desktop/Infinitex/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/Users/jarvismercer/Desktop/Infinitex/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/jarvismercer/Desktop/Infinitex/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.args [as handler] (/Users/jarvismercer/Desktop/Infinitex/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at Object.runCommand (/Users/jarvismercer/Desktop/Infinitex/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/jarvismercer/Desktop/Infinitex/node_modules/yargs/yargs.js:1085:24)
    at Object.get [as argv] (/Users/jarvismercer/Desktop/Infinitex/node_modules/yargs/yargs.js:1000:21)
    at Object.<anonymous> (/Users/jarvismercer/Desktop/Infinitex/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! InfiniTex@0.9.15 dist: `node ./beforePackage.js && cd prod && yarn && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the InfiniTex@0.9.15 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jarvismercer/.npm/_logs/2018-11-02T19_55_19_969Z-debug.log
```

**Comment by fetacore** [comment]
Hey Jarvis sorry I had not seen your issues before (there has not been any activity for some time now).
-The "no hard resets" part is from electron-reload just to make dev easier.
-The lstatsync and chrome flags come from electron itself (I compile with latest beta version in order to take advantage of latest chromium speed).
-For the compilation on macOS I need to configure the electron-builder part of package.json which unfortunately I cannot since I do not have access to a mac. Beware that the command to compile is

```
yarn dist:minify
```
which I guess I should change in the README. Your contribution in the "build" part of package.json for macOS would be very welcome!

Off to the suggestions:
-For the UI I will completely remove the chromium bar and I will try to make the app feel less "web" and more native. I recently came back to this project because I use it for my thesis writing and I still find bugs
-For the UX I was thinking maybe a readthedocs website so that I explain the shortcuts (in general the app is usable even with keyboard only but I never had the courage to write the list of shortcuts).

In any case thank you very much for taking the time to check out the project and I am glad that you like it. I will write in the following 1-2 weeks the contributing file.
